language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.9.7
  - DJANGO_VERSION=1.10.1
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: super_db_administrator/manage.py test
s
